export enum ErrorCode {
    CLIENT_SYSTEM_NOT_FOUND = 'CLIENT_SYSTEM_NOT_FOUND',
    EVENT_TYPE_NOT_FOUND = 'EVENT_TYPE_NOT_FOUND',
    INVALID_CLIENT_TOKEN = 'INVALID_CLIENT_TOKEN',
    VALIDATION_ERROR = 'VALIDATION_ERROR',
    INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
}